version: '3'
services:
  net-worth-tracker-api:
    container_name: net_worth_tracker_api
    build: .
    ports:
      - "23020:23020"
    volumes:
      - ../net-worth-tracker-api:/app
  db:
    container_name: postgres_net_worth_api
    image: postgres:13.2
    restart: unless-stopped
    environment:
        POSTGRES_DB: 'net_worth'
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'rootadmin'
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql
