serve:
  public:
    port: <%= ENV["APP_PORT"] %>

log:
  level: <%= ENV["APP_LOG_LEVEL"] %>

db:
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  name: <%= ENV["DB_NAME"] %>
  user: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  ssl: <%= ENV["DB_SSL"] %>
