openapi: 3.0.3
servers:
  - url: '{scheme}://api.xxx.com'
    variables:
      scheme:
        description: 'The Net Worth tracker REST API is accessible via https and http'
        enum:
          - 'https'
          - 'http'
        default: 'https'
info:
  description: >-
    This API is to serve the new worth platform web and mobile. An REST API built to be fast, flexible and simple.
  version: 1.0.0
  title: Net Worth Tracker API
  contact:
    name: WeNeedThePoh
    url: 'https://github.com/WeNeedThePoh'
paths:
  /sign-in:
    post:
      summary: Social sign-in
      tags:
        - sign-in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/sign_in_post.yaml'
            example:
              $ref: 'examples/sign_in_post.json'
      responses:
        '204':
          description: JWT Token and expire date
          content:
            application/json:
              schema:
                $ref: 'schemas/sign_in_response.yaml'
              example:
                $ref: 'examples/sign_in_response.json'
